# Память для процесса сборки Gradle.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Библиотеки AndroidX вместо устаревшей Support Library.
android.useAndroidX=true

# Стиль кода Kotlin.
kotlin.code.style=official

# Генерировать в R-классе только используемые ресурсы.
android.nonTransitiveRClass=true
